[programs.fzf]
repo          = "junegunn/fzf"
asset_pattern = "fzf-{version}-linux_amd64.tar.gz"
packages      = []

[programs.ripgrep]
repo          = "BurntSushi/ripgrep"
asset_pattern = "ripgrep-{version}-x86_64-unknown-linux-musl.tar.gz"
packages      = []

[programs.tealdeer]
repo          = "tealdeer-rs/tealdeer"
asset_pattern = "tealdeer-linux-x86_64-musl"
packages      = []

[programs.nvim]
repo          = "neovim/neovim"
asset_pattern = "nvim-linux-x86_64.tar.gz"
packages      = []

[programs.kitty]
repo          = "kovidgoyal/kitty"
asset_pattern = "kitty-{version}-x86_64.txz"
packages      = []
